### ISSUE TITLE
TypeError when using react-truncate in a jest-snapshot with react-test-renderer

### ISSUE THREAD

**Issue by JReinhold** [One-com/react-truncate#54]
I get an error when trying to do snapshot-testing with components that has a `<Truncate>`element somewhere in the tree. The error is:

    TypeError: Cannot use 'in' operator to search for 'nodeType' in null
      
      at HTMLBodyElementImpl.appendChild (node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:330:22)
      at HTMLBodyElement.appendChild (node_modules/jsdom/lib/jsdom/living/generated/Node.js:132:57)
      at Truncate.componentDidMount (node_modules/react-truncate/lib/Truncate.CommonJS.js:77:27)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:263:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:209:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:156:16)`

the test that produces the error is:
```
import * as React from 'react';
import * as renderer from 'react-test-renderer';
import Truncate from 'react-truncate';

it('Tests snapshots', () => {
	const snap = renderer.create(<Truncate lines={2}>hello world</Truncate>)
		.toJSON();
	expect(snap).toMatchSnapshot();
});
```

I am using the command `yarn test --env=jsdom` to run the test, which is the default way of doing it when using **create-react-app**.

Anything I'm missing here?

**Comment by richiemccoll** [comment]
I ran into this issue and fixed it by mocking the Truncate component. 

`export default function ReactTruncate({ children }) { 
  return (
    <span>{children}</span>
  );
}`

**Comment by PabloSichert** [comment]
Is that an acceptable workaround for you?

Otherwise, you might want to try again with `react-truncate@2.2` as the dependency on `JSDOM` got updated.

Please reopen if still relevant.
